partition: gpu_partition
nodelist: node1,node2,node3,node4
gpus_per_node: 8
cpus_per_node: 32
multitasks_count: 100
sponge_gpus_per_task: 1
gromacs_gpus_per_task: 8
amber_gpus_per_task: 8
dsdp_gpus_per_task: 1

node_exporter_port: 9100
gpu_exporter_port: 9445
server_ip: 127.0.0.1
server_port: 9090
conda_path: ~/anaconda3
dsdp_env: DSDP