partition: cpu_partition
nodelist: node1,node2,node3,node4
cpus_per_node: 56
multitasks_count: 400
bwa_cpus_per_task: 14
spades_cpus_per_task: 2
bismark_parallel: 1
star_cpus_per_task: 8
cellranger_cpus_per_task: 8
gatk_cpus_per_task: 1
bwa_singlenode_score:
node_exporter_port: 9100
server_ip: 127.0.0.1
server_port: 9090
delete-intermediate-files: false
