partition: gpu_partition
node: node1
gpus: 8
cpus: 48
multitasks_count: 50
repeat: 10
node_exporter_port: 9100
gpu_exporter_port: 9445
server_ip: 127.0.0.1
server_port: 9090
mindsponge_cuda_home: /path/to/cuda-11.6
alphafold_cuda_home: /path/to/cuda-12.6
conda_path: ~/anaconda3
mindsponge_env: mindsponge-gpu
alphafold_env: alphafold3
alphafold_path: /path/to/src/alphafold3
alphafold_param_path: /path/to/af3/parameters
alphafold_db_path: /path/to/af3/public_databases
